### ISSUE TITLE
Not able to import chef on Python 3.4

### ISSUE THREAD

**Issue by ShakeelFluke** [coderanger/pychef#67]
Can you please help me on this error 

Python 3.4.3 (default, Feb 23 2017, 16:35:53)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import chef
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/svellore/workspace/python/flask-code/virtualenvs/py3.4/lib/python3.4/site-packages/PyChef-0.3.0-py3.4.egg/chef/__init__.py", line 6, in <module>
    from chef.client import Client
  File "/Users/svellore/workspace/python/flask-code/virtualenvs/py3.4/lib/python3.4/site-packages/PyChef-0.3.0-py3.4.egg/chef/client.py", line 2, in <module>
    from chef.base import ChefObject
  File "/Users/svellore/workspace/python/flask-code/virtualenvs/py3.4/lib/python3.4/site-packages/PyChef-0.3.0-py3.4.egg/chef/base.py", line 39, in <module>
    class ChefObject(six.with_metaclass(ChefObjectMeta, object)):
  File "/Users/svellore/workspace/python/flask-code/virtualenvs/py3.4/lib/python3.4/site-packages/six-1.6.0-py3.4.egg/six.py", line 627, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Users/svellore/workspace/python/flask-code/virtualenvs/py3.4/lib/python3.4/site-packages/PyChef-0.3.0-py3.4.egg/chef/base.py", line 35, in __init__
    ChefObject.types[name.lower()] = cls
**NameError: name 'ChefObject' is not defined**
>>>

**Comment by coderanger** [comment]
Some details with metaclasses changed in 3.4 that I haven't updated for.

Also, unrelated, but for the love of all that is holy stop using `easy_install` and egg folder installs.

**Comment by ShakeelFluke** [comment]
Thanks for your reply. Can you please suggest me Python and PyChef version for a fresh start.

**Comment by coderanger** [comment]
I mean [tests are all passing on 3.4 and 3.5](https://travis-ci.org/coderanger/pychef/jobs/204705639), so it should work at least somewhat. What does your code look like? I would say uninstall the egg format and try installing normally via `pip`.

**Comment by ShakeelFluke** [comment]
Thank you. I started working on 3.4 and it is working fine 👍
